bump kubernetes-log-watcher to version 0.31
zalando-incubator/kubernetes-on-aws pull request #2405
Opened 2019-08-08 16:08 UTC by pheanex

For details see:
https://github.com/zalando-incubator/kubernetes-log-watcher/commit/f47fa2959df59185352e7d9f6211ef6f883a4e6b

This should lead to less "bytes skipped" for scalyr-agent

2019-08-08 16:09 UTC, pheanex commented
:+1:

2019-08-08 16:14 UTC, anton-ryzhov commented
:+1:

2019-08-09 07:44 UTC, astarnell requested changes
Please also increase the logging_agent_version in cluster/config-defaults.yaml

2019-08-12 07:46 UTC, pheanex commented
> Please also increase the logging_agent_version in cluster/config-defaults.yaml

Done => I wondered if we should also get rid of the "v" prefix for version at some point?!

2019-08-12 07:46 UTC, pheanex commented
:+1:

2019-08-12 14:53 UTC, njuettner commented
👍

2019-08-13 08:58 UTC, astarnell commented
:+1:

2019-08-13 11:29 UTC, aermakov-zalando commented
👍

2019-08-13 11:29 UTC, merged