skipper redis ring conn timeouts
zalando-incubator/kubernetes-on-aws pull request #3928
Opened 2021-01-15 10:39 UTC by szuecs

Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>

2021-01-15 11:06 UTC, mikkeloscar commented
:+1:

2021-01-15 14:00 UTC, jonathanbeber requested changes

2021-01-15 14:00 UTC, jonathanbeber commented on cluster/config-defaults.yaml
> +skipper_redis_write_timout: "25ms"
```suggestion
skipper_redis_pool_timeout: "250ms"
skipper_redis_read_timeout: "25ms"
skipper_redis_write_timeout: "25ms"
```

2021-01-15 14:00 UTC, jonathanbeber commented on cluster/manifests/skipper/deployment.yaml
> +          - "-swarm-redis-write-timeout={{ .ConfigItems.skipper_redis_write_timout }}"
```suggestion
          - "-swarm-redis-pool-timeout={{ .ConfigItems.skipper_redis_pool_timeout }}"
          - "-swarm-redis-read-timeout={{ .ConfigItems.skipper_redis_read_timeout }}"
          - "-swarm-redis-write-timeout={{ .ConfigItems.skipper_redis_write_timeout }}"
```

2021-01-18 08:00 UTC, mikkeloscar commented
:+1:

2021-01-18 14:44 UTC, szuecs commented
:+1:

2021-01-18 14:44 UTC, merged