Enables NLB HTTP redirect
zalando-incubator/kubernetes-on-aws pull request #4651
Opened 2021-09-21 10:21 UTC by AlexanderYastrebov

2021-09-21 13:21 UTC, AlexanderYastrebov commented on cluster/manifests/skipper/deployment.yaml
> +              wget -T 1 -q -O /dev/null http://127.0.0.1:9998/healthz;
TODO: add to `-status-checks`?

2021-09-21 14:05 UTC, szuecs commented on cluster/manifests/skipper/deployment.yaml
> +              wget -T 1 -q -O /dev/null http://127.0.0.1:9998/healthz;
For the redirect listener?
I would say we can omit it, because it's not waiting for an external dependency and we start it before main skipper, so no need for extra safety.

2021-09-21 16:52 UTC, szuecs commented on cluster/cluster.yaml
> +{{- if or (eq .ConfigItems.nlb_switch "pre") (eq .ConfigItems.nlb_switch "exec") }}
We should not guard this here, because it might introduce a race condition. Just put it into the section with kube_aws_ingress_controller_nlb_enabled "true" below and change just FromPort to 9998

2021-09-21 16:57 UTC, AlexanderYastrebov commented on cluster/cluster.yaml
> +{{- if or (eq .ConfigItems.nlb_switch "pre") (eq .ConfigItems.nlb_switch "exec") }}
Do you mean if `kube_aws_ingress_controller_nlb_enabled` is `false`? In that case we need to change all other occurrences  of `nlb_switch` to respect `kube_aws_ingress_controller_nlb_enabled`

2021-09-21 17:00 UTC, szuecs requested changes
Some small but important changes

2021-09-21 17:00 UTC, szuecs commented on cluster/manifests/skipper/deployment.yaml
> +              wget -T 1 -q -O /dev/null http://127.0.0.1:9998/healthz;
Similar to above:
I think we should omit having this livenessProbe change, because it's too much interruption for the redirect case, that should be rarely happen anyways

2021-09-21 17:00 UTC, szuecs commented on cluster/cluster.yaml
> +{{- if or (eq .Cluster.ConfigItems.nlb_switch "pre") (eq .Cluster.ConfigItems.nlb_switch "exec") }}
Don't guard this and add it into the section below only changing FromPort, otherwise we can have a race condition here for no reason.

2021-09-21 17:00 UTC, szuecs commented on cluster/manifests/skipper/deployment.yaml
> +              wget -T 1 -q -O /dev/null http://127.0.0.1:9998/healthz;
please no livenessProbe for this, because we don't want to loose production traffic only because the redirect does not work for a single instance. tokeninfo is different because we serve ~10% of overall traffic with it.

2021-09-21 17:04 UTC, szuecs commented on cluster/cluster.yaml
> +{{- if or (eq .ConfigItems.nlb_switch "pre") (eq .ConfigItems.nlb_switch "exec") }}
Just open the port without guard

2021-09-21 17:20 UTC, AlexanderYastrebov commented on cluster/cluster.yaml
> +{{- if or (eq .ConfigItems.nlb_switch "pre") (eq .ConfigItems.nlb_switch "exec") }}
Fixed

2021-09-21 17:20 UTC, AlexanderYastrebov commented on cluster/manifests/skipper/deployment.yaml
> +              wget -T 1 -q -O /dev/null http://127.0.0.1:9998/healthz;
Removed HTTP redirect liveness probe

2021-09-21 17:23 UTC, szuecs approved these changes
thanks, great PR

2021-09-21 17:23 UTC, szuecs commented
:+1:

2021-09-21 18:15 UTC, AlexanderYastrebov commented
:+1:

2021-09-22 08:50 UTC, aryszka commented
:+1:

2021-09-22 08:50 UTC, merged