Add testcase to ensure ratelimits are working correctly
zalando-incubator/kubernetes-on-aws pull request #5883
Opened 2023-03-30 16:11 UTC by MustafaSaber

Signed-off-by: Mustafa Abdelrahman <mustafa.abdelrahman@zalando.de>

2023-03-30 16:54 UTC, szuecs requested changes
Small changes that should enhance the Test

2023-03-30 16:54 UTC, szuecs commented on test/e2e/routegroup.go
> +				`status(201)`,
The status code you should set in the backend not the RouteGroup

2023-03-30 16:54 UTC, szuecs commented on test/e2e/routegroup.go
> +				`clusterRatelimit("foo", 1, "1s")`,
Not sure if 1s will be too flaky in e2e tests, maybe 5s or so?

2023-03-31 09:11 UTC, MustafaSaber commented on test/e2e/routegroup.go
> +				`clusterRatelimit("foo", 1, "1s")`,
I was going with trail and error here, but yes maybe 5 would be better start

2023-04-04 15:30 UTC, szuecs commented
:+1:

2023-04-04 15:32 UTC, linki commented
👍

2023-04-04 15:57 UTC, szuecs approved these changes

2023-04-04 15:57 UTC, merged